spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activitytracker
    username: root
    password: 7999389177
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9050
